In [3]:
import pandas as pd
import numpy as np 
import yfinance as yf
from datetime import datetime
from datetime import timedelta
from yahoo_earnings_calendar import YahooEarningsCalendar
import dateutil.parser

In [4]:
def getAverage(twtr):
    print("day1: "+str(round(twtr['day1'].mean(),2)))
    print("day2: "+str(round(twtr['day2'].mean(),2)))
    print("day5: "+str(round(twtr['day5'].mean(),2)))
    print("day10: "+str(round(twtr['day10'].mean(),2)))
    print("day20: "+str(round(twtr['day20'].mean(),2)))
    print("day30: "+str(round(twtr['day30'].mean(),2)))
    print("day60: "+str(round(twtr['day60'].mean(),2)))
    print("day90: "+str(round(twtr['day90'].mean(),2)))
    print("day365: "+str(round(twtr['day365'].mean(),2)))
    
def earningsPerformance(ticker):
    #Company Specific earnings 
    # setting the parameters 
    TICKER = ticker
    DAYS_AHEAD = 180

    # setting the dates
    #start_date = datetime.now().date()
    #end_date = (datetime.now().date() + timedelta(days=DAYS_AHEAD))

    start_date = datetime.now().date()- timedelta(days=2500)
    end_date = (datetime.now().date())+timedelta(days= 90)

    # downloading the earnings calendar
    yec = YahooEarningsCalendar()
    earnings_list = yec.get_earnings_of(TICKER)
    earnings_df = pd.DataFrame(earnings_list)

    # extracting the date from the string and filtering for the period of interest
    earnings_df['report_date'] = earnings_df['startdatetime'].apply(lambda x: dateutil.parser.isoparse(x).date())
    earnings_df = earnings_df.loc[earnings_df['report_date'].between(start_date, end_date)] \
                             .sort_values('report_date')

    twtr = earnings_df
    twtr = twtr[twtr['startdatetimetype']=='TNS']
    twtr = twtr[twtr['epsactual'].notnull()]
    twtr = twtr[['ticker','epsestimate','epsactual','epssurprisepct','report_date']]
    #dates after 1,2,5,10,20,60,90
    twtr["day1"] = np.nan
    twtr["day2"] = np.nan
    twtr["day5"] = np.nan
    twtr["day10"] = np.nan
    twtr["day20"] = np.nan
    twtr["day30"] = np.nan
    twtr["day60"] = np.nan
    twtr["day90"] = np.nan
    twtr["day365"] = np.nan
    price = yf.download(TICKER,threads= False, start = '2010-09-21', end = '2021-05-09', interval = '1d')
    #start_date.strftime("%Y-%m-%d")
    for ind,row in twtr.iterrows():
        ilocation = 0 
        curDate = str(row.loc["report_date"])
        #curDate = curDate+" 00:00:00"
        try:
            currentPrice = float(price[price.index == curDate]['Adj Close'][0])
        except:
            pass
        try:
            ilocation = price.index.get_loc(price[price.index == curDate].iloc[0].name)
        except:
            print("location issue")
            pass
        try:
            day1 = price.iloc[ilocation+1]['Adj Close']
        except:
            
            day1 = np.nan
            pass
        try:
            day2 = price.iloc[ilocation+2]['Adj Close']
        except:
            
            day2 = np.nan
            pass
        try:
            day5 = price.iloc[ilocation+5]['Adj Close']
        except:
            
            day5 = np.nan
            pass
        try:
            day10 = price.iloc[ilocation+10]['Adj Close']
        except:
            
            day10 = np.nan
            pass
        try:
            day20= price.iloc[ilocation+20]['Adj Close']
        except:
            
            day20 = np.nan
            pass
        try:
            day30 = price.iloc[ilocation+30]['Adj Close']
        except:
            
            day30 = np.nan
            pass
        try:
            day60 = price.iloc[ilocation+60]['Adj Close']
        except:
            
            day60 = np.nan
            pass
        try:
            day90 = price.iloc[ilocation+90]['Adj Close']
        except:
            
            day90 = np.nan
            pass
        try:
            day365= price.iloc[ilocation+365]['Adj Close']
        except:
            
            day365 = np.nan
            pass


        try:
            twtr.loc[ind,"day1"]= ((day1-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day2'] = ((day2-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day5'] = ((day5-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day10'] = ((day10-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day20'] = ((day20-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day30'] = ((day30-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day60'] = ((day60-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day90'] = ((day90-currentPrice)/currentPrice)*100
        except:
            pass
        try:
            twtr.loc[ind,'day365']=((day365-currentPrice)/currentPrice)*100
        except:
            pass

    getAverage(twtr)
    
    return twtr

In [13]:
earningsPerformance("ttd")

[*********************100%***********************]  1 of 1 completed
location issue
day1: 6.12
day2: 4.31
day5: 4.41
day10: 6.2
day20: 10.32
day30: 9.56
day60: 23.98
day90: 38.48
day365: 194.19

,ticker,epsestimate,epsactual,epssurprisepct,report_date,day1,day2,day5,day10,day20,day30,day60,day90,day365
22,TTD,0.21,0.24,13.21,2016-11-10,8.621427,9.987196,10.670081,24.114381,17.242847,28.681175,20.956038,58.002561,122.407170
21,TTD,0.23,0.33,45.37,2017-02-16,-2.847724,4.916065,11.870501,33.693039,18.435245,11.660669,60.581531,51.408865,152.757788
20,TTD,0.00,0.18,9100.00,2017-05-11,30.107802,34.294311,28.804216,30.333423,28.754077,35.898721,39.157682,54.725501,211.857617
19,TTD,0.19,0.52,181.08,2017-08-10,8.769475,7.151414,-3.375954,1.877744,12.325206,19.456647,29.085100,-0.519381,169.756272
18,TTD,0.28,0.35,27.27,2017-11-09,-13.976046,-18.345142,-17.510117,-13.647099,-23.667340,-22.031035,-25.438594,-8.029687,263.090435
17,TTD,0.43,0.54,24.71,2018-02-22,23.842968,18.533052,12.231401,19.669414,12.644625,-1.487606,76.921476,94.628087,420.392535
16,TTD,0.10,0.34,240.00,2018-05-10,43.390861,42.082304,52.550736,57.386684,68.063728,74.587518,69.049877,174.473728,259.965862
15,TTD,0.44,0.60,37.30,2018-08-09,37.131524,34.730412,36.391893,46.532314,52.181370,52.063457,37.152959,32.725907,200.557414
14,TTD,0.50,0.65,30.00,2018-11-08,0.302785,-9.222583,0.932896,-2.332241,10.270052,-14.574466,16.235677,66.047470,110.008193
13,TTD,0.80,1.09,37.11,2019-02-21,31.390782,31.317687,31.264527,25.456838,41.916406,31.570199,31.583492,55.339222,215.848222
12,TTD,0.25,0.49,99.19,2019-05-09,-3.375107,-6.929235,6.381632,2.827504,29.022744,27.074557,31.518535,12.284121,225.552856
11,TTD,0.69,0.95,38.08,2019-08-08,-0.632152,-6.792857,-11.016921,-5.053538,-14.813464,-24.343190,-25.786533,-7.245959,196.338638
10,TTD,0.67,0.75,12.61,2019-11-07,1.442282,12.586249,18.329443,24.549939,28.326851,36.835279,49.167309,-13.130997,263.284037
9,TTD,1.17,1.49,27.79,2020-02-27,14.895407,15.239387,8.463669,-22.943083,-16.383342,-14.499420,23.035084,80.276789,NaN
8,TTD,0.42,0.90,116.35,2020-05-07,-2.170543,-5.324035,-7.813957,-5.606197,9.857367,22.412403,47.386049,38.077516,NaN
7,TTD,0.17,0.92,447.62,2020-08-06,2.589706,-3.124283,-1.853355,-2.182005,-3.348935,-9.360374,17.826316,91.871031,NaN
6,TTD,0.43,1.27,196.04,2020-11-05,26.578100,17.622433,14.321028,24.504866,39.623057,46.995214,29.638505,8.156958,NaN
5,TTD,1.88,3.71,97.55,2021-02-18,6.715886,-0.151214,-10.857646,-24.375668,-17.294746,-22.168928,NaN,NaN,NaN
4,TTD,0.77,1.41,83.59,2021-05-10,-96.585942,-96.732428,-96.055523,-97.072652,-96.992321,-97.113999,-96.512699,-96.496161,-93.149439